# Generated by Django 3.2.4 on 2021-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('word', models.CharField(max_length=512, primary_key=True, serialize=False)),
            ],
        ),
    ]
